# Generated by Django 4.2.6 on 2023-11-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_remove_historialperformance_deliverydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgementDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
