# Generated by Django 4.2.6 on 2023-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_alter_purchaseorder_acknowledgementdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialperformance',
            name='onTimeDeliveryRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
