# Generated by Django 4.2.6 on 2023-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_alter_historialperformance_ontimedeliveryrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialperformance',
            name='averageResponseTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialperformance',
            name='fulfillmentRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialperformance',
            name='qualityRatingAvg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
