# Import necessary modules from Django
from django.urls import path, include

# Import views and models from the current application
from .views import vendorViewset, purchaseOrderViewset, performanceViewset

# Import Django REST Framework routers
from rest_framework import routers

# Create a DefaultRouter instance
router = routers.DefaultRouter()

# Register the 'vendorViewset' under the endpoint 'vendors'
router.register(r'vendors', vendorViewset)

# Register the 'purchaseOrderViewset' under the endpoint 'purchaseOrders'
router.register(r'purchaseOrders', purchaseOrderViewset)

# Register the 'performanceViewset' under the endpoint 'performances'
router.register(r'performances', performanceViewset)

# Define the URL patterns for the application
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]


# api/vendors -- GET -- Retrieve all vendors
# api/vendors/{vendor_id} -- GET -- Retrieve a specific vendor
# api/vendors/{vendor_id} -- PUT -- Update a specific vendor
# api/vendors/{vendor_id} -- DELETE -- Delete a specific vendor
# api/vendors/{vendor_id}/purchaseOrders -- GET -- Retrieve all purchase orders for a specific vendor
# api/purchaseOrders -- GET -- Retrieve all purchase orders
# api/purchaseOrders/{purchaseOrder_id} -- GET -- Retrieve a specific purchase order
# api/purchaseOrders/{purchaseOrder_id} -- PUT -- Update a specific purchase order
# api/purchaseOrders/{purchaseOrder_id} -- DELETE -- Delete a specific purchase order
# api/performances -- GET -- Retrieve all historical performances
# api/performances/{performance_id} -- GET -- Retrieve a specific historical performance
# api/performances/{performance_id} -- PUT -- Update a specific historical performance
# api/performances/{performance_id} -- DELETE -- Delete a specific historical performance
# api/vendors/{vendor_id}/performance -- GET -- Retrieve historical performance data for a specific vendor